"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-04-23

Creates every table described in src/app/models. Written by hand (rather
than autogenerated) so the migration stays legible when reviewed.
"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=16), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.UniqueConstraint("email", name="uq_users_email"),
    )
    op.create_index("ix_users_email", "users", ["email"], unique=True)

    op.create_table(
        "categories",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("display_order", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.UniqueConstraint("name", name="uq_categories_name"),
    )

    op.create_table(
        "menu_items",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("description", sa.String(length=1000), nullable=True),
        sa.Column("prep_time_minutes", sa.Integer(), nullable=False, server_default="0"),
        sa.Column("is_daily_special", sa.Boolean(), nullable=False, server_default=sa.false()),
        sa.Column("is_active", sa.Boolean(), nullable=False, server_default=sa.true()),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"], ["categories.id"],
            ondelete="RESTRICT",
            name="fk_menu_items_category_id",
        ),
    )
    op.create_index("ix_menu_items_category_id", "menu_items", ["category_id"])

    op.create_table(
        "prices",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("menu_item_id", sa.Integer(), nullable=False),
        sa.Column("amount_cents", sa.Integer(), nullable=False),
        sa.Column("effective_from", sa.DateTime(timezone=True), nullable=False),
        sa.Column("effective_to", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["menu_item_id"], ["menu_items.id"],
            ondelete="CASCADE",
            name="fk_prices_menu_item_id",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"],
            ondelete="RESTRICT",
            name="fk_prices_created_by",
        ),
    )
    op.create_index("ix_prices_menu_item_id", "prices", ["menu_item_id"])
    op.create_index("ix_prices_item_open", "prices", ["menu_item_id", "effective_to"])

    op.create_table(
        "menus",
        sa.Column("id", sa.Integer(), primary_key=True),
        sa.Column("name", sa.String(length=150), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("archived_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"],
            ondelete="RESTRICT",
            name="fk_menus_created_by",
        ),
        sa.UniqueConstraint("name", "version", name="uq_menu_name_version"),
    )

    op.create_table(
        "menu_item_in_menu",
        sa.Column("menu_id", sa.Integer(), nullable=False),
        sa.Column("menu_item_id", sa.Integer(), nullable=False),
        sa.Column("price_id", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("menu_id", "menu_item_id", "price_id"),
        sa.ForeignKeyConstraint(
            ["menu_id"], ["menus.id"],
            ondelete="CASCADE",
            name="fk_mim_menu_id",
        ),
        sa.ForeignKeyConstraint(
            ["menu_item_id"], ["menu_items.id"],
            ondelete="RESTRICT",
            name="fk_mim_menu_item_id",
        ),
        sa.ForeignKeyConstraint(
            ["price_id"], ["prices.id"],
            ondelete="RESTRICT",
            name="fk_mim_price_id",
        ),
    )


def downgrade() -> None:
    op.drop_table("menu_item_in_menu")
    op.drop_table("menus")
    op.drop_index("ix_prices_item_open", table_name="prices")
    op.drop_index("ix_prices_menu_item_id", table_name="prices")
    op.drop_table("prices")
    op.drop_index("ix_menu_items_category_id", table_name="menu_items")
    op.drop_table("menu_items")
    op.drop_table("categories")
    op.drop_index("ix_users_email", table_name="users")
    op.drop_table("users")
